version: "3.8"

services:

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - "40801:80"
    volumes:
      - "/root/nginx.conf:/etc/nginx/nginx.conf:ro"

  nps:
    container_name: nps
    image: ffdfgdfg/nps:latest
    restart: always
    volumes:
      - "/root/nps:/conf"
    network_mode: host

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    ports:
     - "8080:8080"
