version: "3"

services:
  freshrss:
    image: freshrss/freshrss
    restart: always
    ports:
      - "80:80"
    volumes:
      - /root/rssreader:/var/www/FreshRSS/data
    environment:
      - CRON_MIN=*/20
      - TZ=Asia/Shanghai
